service: lambda-delete-empty-logstream
frameworkVersion: '3'
provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: ap-northeast-1
  deploymentBucket: serverless-upload-ap-northeast-1
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "logs:DescribeLogGroups"
            - "logs:DescribeLogStreams"
            - "logs:DeleteLogStream"
          Resource: "*"

functions:
  main:
    handler: handler.main
    description: Delete old and empty logstream
    timeout: 300
    events:
      - schedule: rate(1 day)

resources:
  Description: Delete old and empty logstream
